rayon-rs/either

.gitignore, src/lib.rs
The new macros `left!` and `right!` provide means to extract both sides
of an `Either`, if available, or return early with the opposite side.
These macros correspond to an unbiased version of `try!`.
=> Add unwrapping macros that might fail early

src/lib.rs
Added documentation for the methods defined on `Either`, and a few more convenience methods to bring it closer to the functionality provided by `Option` and `Result`.
=> Documentation, inline-hints, `either`, `map_left` and `map_right`

src/lib.rs
Adds an `Extend` `impl` and a variety of `Iterator` method overrides (like the existing `fold` one).
=> Iterator extensions

Cargo.toml
Added categories, so that this package shows up on the [categories page](https://crates.io/categories).
=> Add crates.io categories to Cargo.toml

src/lib.rs
map_* functions always rewrap the result of invoking the provided closure with the corresponding variant. and_then_* functions require the closure to specify the wrapping variant. This allows the closure to change a `Left` into a `Right` or a `Right` into a `Left`.
=> and_then_*

src/lib.rs
This generalization of `either` is necessary to encode some projections.  Essentially the `Ctx` argument to `either_with` encodes the fact that only one of the two functions will be called, which is an otherwise inexpressible fact with `either`.
=> add an either_with with shared context

src/lib.rs
This adds an `into_iter(self)` method which converts the inner values to
iterators with `IntoIterator`.
Unfortunately, this can't be done with `IntoIterator` for `Either`
itself because of the blanket `impl<I: Iterator> IntoIterator for I`,
and `Either` conditionally implements `Iterator`.
=> Add a method to convert Either to an iterator

src/lib.rs
Implementing it through `either_with` just makes more work for the
compiler with the extra closures, and provides no real value to us.
A direct `match` is easy enough.
=> Flatten the implementation of Either::either

src/lib.rs
In library routines, these patterns may appear commonly. It can be
useful to extract out the common parts for further processing and may
also allow the remaining `Either` type to be used via traits.
Fixes #17.
=> add methods to handle homogeneous types

Cargo.toml, README.rst, src/lib.rs
As discussed in #28 
I've also made tests to make sure that we are getting what we really want to. On the other hand the functionality and implementation is so simple and straightforward, while the tests are a little bit clumsy (especially for `AsMut<str>`), so I'm hesitating on whether or not we should keep them.
=> Implement `AsRef` and `AsMut` for `str`, `[T]` and some other unsized types

src/lib.rs
Fixes: https://github.com/bluss/either/issues/41
=> fix: allow bare_trait_objects

src/lib.rs
`Error::description` has been documented as soft-deprecated since 1.27.0 (17 months ago). It is going to be hard-deprecated soon.
This PR:
- Allows deprecated Error::description
Related PR: https://github.com/rust-lang/rust/pull/66919
=> Allow deprecated Error::description

.travis.yml, Cargo.toml, src/lib.rs, src/serde_untagged.rs, src/serde_untagged_optional.rs
Unfortunately, adding serde(untagged) to Either would be breaking change.
This PR instead provides two functions, that can be used in conjunction with serde(with) to achieve quite untagged representation at user choice.
=> Add special utitilies for serde untagged repr

Cargo.toml, README.rst, src/lib.rs
References:
- [`Result::unwrap`](https://doc.rust-lang.org/std/result/enum.Result.html#method.unwrap)
- [`Result::expect`](https://doc.rust-lang.org/std/result/enum.Result.html#method.expect)
- [`Result::unwrap_err`](https://doc.rust-lang.org/std/result/enum.Result.html#method.unwrap_err)
- [`Result::expect_err`](https://doc.rust-lang.org/std/result/enum.Result.html#method.expect_err)
Hello :wave: 
While the behavior of `unwrap` and `expect` can be achieved with `x.left().expect("should be left")`, `x.left_or_else(|_| panic!("should be left"))`, or `match`, I was wondering if these methods should be implemented on `Either` directly, since the README says
>Either has methods that are similar to Option and Result
and `unwrap` and `expect` are fairly commonly used on `Option` and `Result` …
=> Feature: `unwrap_left` `unwrap_right` `expect_left` `expect_right`

src/lib.rs
See commit messages for details.
Resolves #57.
I've added d4f231d0fcfc91816189091e3870834a9044d513 at the very end as a suggestion. Happy to drop it if it is undesired. My rationale was that a closure like syntax is 
a) more inuitive
b) less error prone
If we allow the user to specify _patterns_, they might actually run into a situation where they produce a non-exhaustive `match`. If there is consensus, I can migrate the entire crate to use closure-like syntax but I wanted to get feedback on the idea first.
=> Publicly expose `either` macro as `for_both`

src/lib.rs
This pull request implements [the io::Seek trait](https://doc.rust-lang.org/std/io/trait.Seek.html) on Either when `L` and `R` implements it.
=> Implement the io::Seek trait

.github/workflows/ci.yml, src/lib.rs, src/serde_untagged.rs, src/serde_untagged_optional.rs
I think this may not work with the current 1.12.0 MSRV but I wanted to open this anyway to start a discussion.
Without the `source` impl, the `Error` impl is not dramatically useful. All "modern" error handling libraries like `anyhow` operate on `source`.
New MSRV would be 1.37 with this change.
=> Override `source` in the Error impl

src/lib.rs
Similar to `Either::factor_first`/`factor_second`, and `Result`/`Option::transpose` (though those lose no information).
`Either::factor_none` takes an `Either<Option<L>, Option<R>>` and gives an `Option<Either<L, R>>`,
merging `Left(None)` and `Right(None)` into `None`.
~~`Either::factor_error`~~ `Either::factor_err` takes an `Either<Result<L, E>, Result<R, E>>` and gives an `Result<Either<L, R>, E>`,
merging `Left(Err(e))` and `Right(Err(e))` into `Err(e)`.
`Either::factor_ok` takes an `Either<Result<T, L>, Result<T, R>>` and gives an `Result<T, Either<L, R>>`,
merging `Left(Ok(t))` and `Right(Ok(t))` into `Ok(t)`.
=> Feature: add methods to factor common Result and Option types.

src/lib.rs
Resolves #65
Delegates directly to the inner iterators, as these implementations may be more performant/generate less LLVM IR than the blanket impls:
- `DoubleEndedIterator::nth_back`
- `DoubleEndedIterator::rfold`
- `ExactSizeIterator::len`
=> Add missing specializations on `Iterator` impl

src/lib.rs
- Specialize more `Iterator` methods
- Specialize `DoubleEndedIterator::rfind`
- Implement `FusedIterator`
=> Expand iterator coverage

.github/workflows/ci.yml
- Update to actions/checkout@v3
- Switch from actions-rs/toolchain to dtolnay/rust-toolchain
- Switch from actions-rs/cargo to plain run
=> Update and simplify the CI workflow

src/lib.rs
Some types override these methods to provide optimizations. Using
default implementations would bypass those overrides and lead to worse
performance.
Overriding the methods to delegate implementations directly solves the
problem.
=> Override `read_exact` and `write_all`

.github/workflows/ci.yml, Cargo.toml, README.rst, src/lib.rs
=> Add `Pin` projections and implement `Future` (MSRV 1.36)

Cargo.toml, README.rst
This change fixes the license field to valid SPDX. 
[Documentation](https://doc.rust-lang.org/cargo/reference/manifest.html#the-license-and-license-file-fields) says that SPDX license expressions support AND and OR operators to combine multiple licenses. Previously multiple licenses could be separated with a /, but that usage is deprecated.
It is currently causing dependency reviews to fail like:
=> Changes Cargo license field to valid SPDX

.github/workflows/ci.yml, Cargo.toml, README.rst, src/lib.rs
This PR adds the `map_either` and `map_either_with` variants to the library. Closes #81
=> Add map_either and map_either_with methods

.github/workflows/ci.yml, README.rst
This is copied from how rust-lang/miri-test-libstd does it.
=> ci: rewrite the success job

src/iterator.rs, src/lib.rs
=> add factor_iter() and iter() methods

src/into_either.rs, src/lib.rs
Add:
+ Trait `IntoEither`
- `into_either`: Conditionally convert any sized type into any variant of `Either`.
- `into_either_with`: Like `into_either`, but takes a predicate function instead.
+ Impl `IntoEither` for generic type `T`, where `T` is `Sized`
Close #99
=> Feat: Implement trait `IntoEither`

.github/workflows/ci.yml, Cargo.toml, README.rst, src/iterator.rs
The commented-out implementations of `nth_back` have had a `TODO(MSRV)` for a while, since that requires Rust 1.37. The main reason we held back on 1.36 was for `itertools`, but they've required 1.43 since `itertools v0.11.0` published 6 months ago. I don't see any other functionality in that range that would be useful to `either` though, so we might as well stick to the minimal bump here.
=> Specialize `nth_back` (MSRV 1.37)

src/lib.rs
Similar to Option::cloned and Option::copied, these methods will clone or copy the contents of an Either containing references on both sides.
=> Add Either::cloned and Either::copied

src/lib.rs
Found myself needing this (while working on `rustdoc`).
=> Impl `fmt::Write` for `Either`

.github/workflows/ci.yml, Cargo.toml
=> Bump MSRV up to 1.63

src/iterator.rs, src/lib.rs
Some of the code in this crate is around a decade old, which means it couldn't use the ergonomic benefits afforded by [RFC 2005](https://rust-lang.github.io/rfcs/2005-match-ergonomics.html) (which was stabilized around 2017 or 2018).
So now instead of doing `match *thing { ref mut thing => { ... } }`, we can just do `match thing { thing => { ... } }`.
See discussion here: https://github.com/rayon-rs/either/pull/113#discussion_r1958234427
=> Simplify match patterns to be more ergonomic

.github/workflows/ci.yml, Cargo.toml, src/lib.rs
Closes https://github.com/rayon-rs/either/issues/26
Adds a more common `std` alias for `use_std` feature and disables default features for serde crate thus fixing no-std support for compilation with `serde` enabled
=> fix: no-std with serde feature
